name: Auto rebase branches

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Read config file
        id: config
        run: |
          BASE=$(jq -r '.base' .github/rebase-branches.json)
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "Base branch: $BASE"
        
      - name: Fetch all branches
        run: |
          git fetch origin
          BRANCHES=$(git branch -r | grep 'origin/' | grep -v "origin/HEAD" | grep -v "origin/$BASE" | sed 's#origin/##')
          echo "Fetched branches:"

          while read -r branch; do
            echo " - $branch"
          done <<< "$BRANCHES"
      
      - name: Rebase branches onto ${{ env.BASE }}
        continue-on-error: true # in caz de conflict sa nu se opreasca
        run: |
          while read -r branch; do
            echo "Rebasing branch: $branch"
            git checkout $branch
            if git rebase origin/${{ env.BASE }}; then
              git push origin $branch --force-with-lease
              echo "Rebased and pushed $branch"
            else
              echo "Conflict on $branch"
              git rebase --abort
            fi
          done <<< "$BRANCHES"