name: Automatic rebase branches

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Branch to rebase onto"
        required: false # daca nu e specificat, se face rebase pe toate branch-urile

permissions:
  contents: write

jobs:
  rebase:
    # renovate: depName=ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        # renovate: datasource=github-tags depName=actions/checkout versioning=loose
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Read config file
        run: |
          BRANCHES=$(jq -c '.' .github/rebase-branches.json)
          echo "BRANCHES=$BRANCHES" >> $GITHUB_ENV
          echo "Branches to rebase: $BRANCHES"

      - name: Run automatic rebase
        continue-on-error: true # in caz de conflict sa nu se opreasca
        run: |
          echo '${{env.BRANCHES}}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r BRANCH BASE; do
            
            if [[ -n "${{ github.event.inputs.base_branch }}" ]]; then
              BASE="${{ github.event.inputs.base_branch }}"
            fi
          
            echo "Rebasing branch: $BRANCH onto base: $BASE"
            # git checkout -B "$BRANCH" "origin/$BRANCH"

            # if git rebase "origin/$BASE"; then
            #   git push origin "$BRANCH" --force-with-lease
            #   echo "Rebased $BRANCH onto $BASE"
            # else
            #   echo "Rebased aborted: branch = $BRANCH, base = $BASE"
            #   git rebase --abort
            # fi

            echo "-----------------------------------"
          done